language: node_js
node_js: "6"
services: mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("Admin", "pohutukawa2017");'
cache:
  directories:
    - "node_modules"
before_deploy: "webpack"
deploy:
  provider: heroku
  app: booking
  skip_cleanup: true
  api_key:
    secure: 04af2270-3e6e-4131-ab9d-446486696bdd